### ISSUE TITLE
FM Data missing

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-props-service#3]
From the official sqlite db databases generated... it looks like your tables schema might be a little different.

For example, the official attrib table looks like this...

CREATE TABLE _objects_attr (
    id                INTEGER PRIMARY KEY,
    name              TEXT,
    category          TEXT,
    data_type         INTEGER,
    data_type_context TEXT,
    description       TEXT,
    display_name      TEXT,
    flags             INTEGER,
    display_precision INTEGER,
    UNIQUE (
        name,
        category,
        data_type,
        data_type_context,
        description,
        display_name,
        flags,
        display_precision
    )
);

There's data in the attribs.json file that's not being copied over into the props-sqlite attrib table that's useful.

For example, here's the attribs data showing the missing "FM-Data", display name, such as "Demo_GUID", "Demo_Floor" etc.

Maybe create the table names based on the official sqlite.db and populate the missing fields (even though they don't appear to be used in the pipeline.md docs)

["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_GUID",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Discipline",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_TypeCode",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Category",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Tag",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Type",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_ObjectType",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Name",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Description",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Facility",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Floor",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Model",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Manufacturer",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_OperationalStatus",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Omniclasstitle",0,0],
["LcOdpDBDatabaseReadLink:LcOdpDBDatabaseField","FM Data",20,null,null,"Demo_Omniclassnumber",0,0],

**Comment by wallabyway** [comment]
![sqlite-attribs-differences](https://user-images.githubusercontent.com/440241/117907149-1f48e000-b28b-11eb-9cc1-a40a91b84b7d.jpg)

**Comment by wallabyway** [comment]
https://github.com/petrbroz/forge-props-service/blob/cf7018f1c93ad14b22686bdb3f882e7ed94d6d2a/database.js#L25

db.run('CREATE TABLE objects_attrs (
id INTEGER PRIMARY KEY,
name TEXT,
category TEXT,
data_type INTEGER,
data_type_context TEXT,
description TEXT,
display_name TEXT,
flags INTEGER,
display_precision INTEGER
');

and 

https://github.com/petrbroz/forge-props-service/blob/cf7018f1c93ad14b22686bdb3f882e7ed94d6d2a/database.js#L39

```
const query = `INSERT INTO objects_attrs VALUES ${page.map(_ => '(?, ?, ?, ?, ?, ?, ?, ?, ?)').join(',')};`;
```

**Comment by wallabyway** [comment]
ie..

```
        debug('Creating tables');
        db.run('CREATE TABLE objects_avs (ent_id INTEGER, attr_id INTEGER, val_id INTEGER);');
        db.run('CREATE TABLE objects_ids (ent_id INTEGER PRIMARY KEY, external_id TEXT);');
        db.run('CREATE TABLE objects_attrs ( id INTEGER PRIMARY KEY, name TEXT, category TEXT, data_type INTEGER, data_type_context TEXT, description TEXT, display_name TEXT);');
        db.run('CREATE TABLE objects_vals (val_id INTEGER PRIMARY KEY, value TEXT);');

        debug('Inserting objects_ids');
        for (let i = 1, len = pdb._ids.length; i < len; i += PAGE_SIZE) {
            const page = pdb._ids.slice(i, Math.min(i + PAGE_SIZE, len));
            const query = `INSERT INTO objects_ids VALUES ${page.map(_ => '(?, ?)').join(',')};`;
            const params = page.reduce((prev, curr, index) => { prev.push(i + index, curr); return prev; }, []);
            db.run(query, params);
        }

        debug('Inserting objects_attrs');
        for (let i = 1, len = pdb._attrs.length; i < len; i += PAGE_SIZE) {
            const page = pdb._attrs.slice(i, Math.min(i + PAGE_SIZE, len));
            const query = `INSERT INTO objects_attrs VALUES ${page.map(_ => '( ?, ?, ?, ?, ?, ?, ? )').join(',')};`;
            const params = page.reduce((prev, curr, index) => { prev.push(i + index, curr[0], curr[1], curr[2], curr[3], curr[4], curr[5]); return prev; }, []);
            db.run(query, params);
        }
```

**Comment by wallabyway** [comment]
but there's still missing rows of data, being skipped

**Comment by wallabyway** [comment]
maybe something that streams the file, line by line, into sqlite...

```
const { createDatabase } = require('../database');
const lineReader = require('line-reader');
const sqlite3 = require('sqlite3').verbose();

function convert(inputDir, outputFile) {
    const db = new sqlite3.Database(outputFile);
    db.serialize(function () {
        db.run('PRAGMA journal_mode = off;');
        db.run('PRAGMA synchronous = off;');
        db.run('CREATE TABLE objects_attrs ( id INTEGER PRIMARY KEY, name TEXT, category TEXT, data_type INTEGER, data_type_context TEXT, description TEXT, display_name TEXT, precision INTEGER);');
    
        const query = `INSERT INTO objects_attrs VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )`;
        lineReader.eachLine(path.join(inputDir, 'objects_attrs.json'), function(line, isLast) {
            if (line.length < 4) return;
            if (isLast) { 
                db.close();                
                return;
            }
            const curr = (line.slice(-1)=="]") ? line : line.slice(0,-1);
            const params = JSON.parse(curr);
            db.run(query, params);
        });
    });
};
```

**Comment by petrbroz** [comment]
Thanks Michael, I only noticed this thread after implementing a fix :) I'm still parsing the JSON files instead of streaming them, but the `display_name` vs `name` issue is now resolved. The streaming is a good idea for a potential performance/mem-footprint enhancement, but let's discuss that one separately.
